#!/bin/sh
set -eu

: "${STUDHACK_AUTH_ISSUER:=https://auth.nachert.art/api/v1}"
: "${STUDHACK_AUTH_CLIENT_ID:=5caecabfac74b7709d102315ca3abc9b}"
: "${STUDHACK_AUTH_CLIENT_SECRET:=0f756a3707762ec4d04df5625adcac6a}"
: "${STUDHACK_API_BASE_URL:=https://studhack-api.nachert.art}"
: "${STUDHACK_AUTH_REDIRECT_URI:=}"
: "${STUDHACK_AUTH_POST_LOGOUT_REDIRECT_URI:=}"
: "${STUDHACK_AUTH_DISABLE_NONCE_CHECK:=true}"
: "${STUDHACK_AUTH_DISABLE_OAUTH2_STATE_CHECK:=true}"

export STUDHACK_AUTH_ISSUER
export STUDHACK_AUTH_CLIENT_ID
export STUDHACK_AUTH_CLIENT_SECRET
export STUDHACK_API_BASE_URL
export STUDHACK_AUTH_REDIRECT_URI
export STUDHACK_AUTH_POST_LOGOUT_REDIRECT_URI
export STUDHACK_AUTH_DISABLE_NONCE_CHECK
export STUDHACK_AUTH_DISABLE_OAUTH2_STATE_CHECK

envsubst \
  '${STUDHACK_AUTH_ISSUER} ${STUDHACK_AUTH_CLIENT_ID} ${STUDHACK_AUTH_CLIENT_SECRET} ${STUDHACK_API_BASE_URL} ${STUDHACK_AUTH_REDIRECT_URI} ${STUDHACK_AUTH_POST_LOGOUT_REDIRECT_URI} ${STUDHACK_AUTH_DISABLE_NONCE_CHECK} ${STUDHACK_AUTH_DISABLE_OAUTH2_STATE_CHECK}' \
  < /opt/studhack/runtime-config.template.js \
  > /usr/share/nginx/html/runtime-config.js
