// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudHack.DataAccess.Context;

#nullable disable

namespace StudHack.DataAccess.Migrations
{
    [DbContext(typeof(StudHackDbContext))]
    partial class StudHackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudHack.DataAccess.Models.AdditionalPositionDataDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("AdditionalPositionDataItems");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.AdditionalPositionSkillDb", b =>
                {
                    b.Property<Guid>("AdditionalPositionDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("AdditionalPositionDataId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("AdditionalPositionSkills");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.CityDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EducationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Degree")
                        .HasColumnType("integer");

                    b.Property<string>("Faculty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.HasIndex("UserDbId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EventDateDb", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "StartsAt");

                    b.ToTable("EventDates");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EventDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("RegistrationLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.HackatonDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxTeamSize")
                        .HasColumnType("integer");

                    b.Property<int>("MinTeamSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Hackatons");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.MandatoryPositionDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HackatonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HackatonId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("MandatoryPositions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.MandatoryPositionSkillDb", b =>
                {
                    b.Property<Guid>("MandatoryPositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("MandatoryPositionId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("MandatoryPositionSkills");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.PortfolioLinkDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PortfolioLinks");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.RegionDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.SkillDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.SpecializationDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.SubscriptionDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptainId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("HackatonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("HackatonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamPositionDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdditionalPositionDataId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FilledByExternal")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MandatoryPositionDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalPositionDataId");

                    b.HasIndex("MandatoryPositionDataId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamPositions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamRequestDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamPositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamPositionId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamRequests");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UniversityDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CityOfResidenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthId")
                        .IsUnique();

                    b.HasIndex("CityOfResidenceId");

                    b.HasIndex("UniqueName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserSkillDb", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserSpecializationDb", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("UserSpecializations");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.AdditionalPositionDataDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.SpecializationDb", "Specialization")
                        .WithMany("AdditionalPositionDataItems")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.AdditionalPositionSkillDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.AdditionalPositionDataDb", "AdditionalPositionData")
                        .WithMany("AdditionalPositionSkills")
                        .HasForeignKey("AdditionalPositionDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.SkillDb", "Skill")
                        .WithMany("AdditionalPositionSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdditionalPositionData");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.CityDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.RegionDb", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EducationDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.UniversityDb", "University")
                        .WithMany("Educations")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", null)
                        .WithMany("Educations")
                        .HasForeignKey("UserDbId");

                    b.Navigation("University");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EventDateDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.EventDb", "Event")
                        .WithMany("EventDates")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EventDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.CityDb", "City")
                        .WithMany("Events")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.HackatonDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.EventDb", "Event")
                        .WithOne("Hackaton")
                        .HasForeignKey("StudHack.DataAccess.Models.HackatonDb", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.MandatoryPositionDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.HackatonDb", "Hackaton")
                        .WithMany("MandatoryPositions")
                        .HasForeignKey("HackatonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.SpecializationDb", "Specialization")
                        .WithMany("MandatoryPositions")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hackaton");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.MandatoryPositionSkillDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.MandatoryPositionDb", "MandatoryPosition")
                        .WithMany("MandatoryPositionSkills")
                        .HasForeignKey("MandatoryPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.SkillDb", "Skill")
                        .WithMany("MandatoryPositionSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MandatoryPosition");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.PortfolioLinkDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.UserDb", "User")
                        .WithMany("PortfolioLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.SubscriptionDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.EventDb", "Event")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.UserDb", "Captain")
                        .WithMany("CaptainTeams")
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", "Creator")
                        .WithMany("CreatedTeams")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.HackatonDb", "Hackaton")
                        .WithMany("Teams")
                        .HasForeignKey("HackatonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("Creator");

                    b.Navigation("Hackaton");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamPositionDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.AdditionalPositionDataDb", "AdditionalPositionData")
                        .WithMany("TeamPositions")
                        .HasForeignKey("AdditionalPositionDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudHack.DataAccess.Models.MandatoryPositionDb", "MandatoryPositionData")
                        .WithMany("TeamPositions")
                        .HasForeignKey("MandatoryPositionDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudHack.DataAccess.Models.TeamDb", "Team")
                        .WithMany("TeamPositions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", "User")
                        .WithMany("TeamPositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdditionalPositionData");

                    b.Navigation("MandatoryPositionData");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamRequestDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.TeamPositionDb", "TeamPosition")
                        .WithMany("TeamRequests")
                        .HasForeignKey("TeamPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", "User")
                        .WithMany("TeamRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UniversityDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.CityDb", "City")
                        .WithMany("Universities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.CityDb", "CityOfResidence")
                        .WithMany("Users")
                        .HasForeignKey("CityOfResidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CityOfResidence");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserSkillDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.SkillDb", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserSpecializationDb", b =>
                {
                    b.HasOne("StudHack.DataAccess.Models.SpecializationDb", "Specialization")
                        .WithMany("UserSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudHack.DataAccess.Models.UserDb", "User")
                        .WithMany("UserSpecializations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.AdditionalPositionDataDb", b =>
                {
                    b.Navigation("AdditionalPositionSkills");

                    b.Navigation("TeamPositions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.CityDb", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Universities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.EventDb", b =>
                {
                    b.Navigation("EventDates");

                    b.Navigation("Hackaton");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.HackatonDb", b =>
                {
                    b.Navigation("MandatoryPositions");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.MandatoryPositionDb", b =>
                {
                    b.Navigation("MandatoryPositionSkills");

                    b.Navigation("TeamPositions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.RegionDb", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.SkillDb", b =>
                {
                    b.Navigation("AdditionalPositionSkills");

                    b.Navigation("MandatoryPositionSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.SpecializationDb", b =>
                {
                    b.Navigation("AdditionalPositionDataItems");

                    b.Navigation("MandatoryPositions");

                    b.Navigation("UserSpecializations");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamDb", b =>
                {
                    b.Navigation("TeamPositions");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.TeamPositionDb", b =>
                {
                    b.Navigation("TeamRequests");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UniversityDb", b =>
                {
                    b.Navigation("Educations");
                });

            modelBuilder.Entity("StudHack.DataAccess.Models.UserDb", b =>
                {
                    b.Navigation("CaptainTeams");

                    b.Navigation("CreatedTeams");

                    b.Navigation("Educations");

                    b.Navigation("PortfolioLinks");

                    b.Navigation("Subscriptions");

                    b.Navigation("TeamPositions");

                    b.Navigation("TeamRequests");

                    b.Navigation("UserSkills");

                    b.Navigation("UserSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
