when:
  - event: pull_request
    path:
      include:
        - .woodpecker/studhack-ui.yml
        - studhack-ui/**

  - event: push
    branch: main
    path:
      include:
        - .woodpecker/studhack-ui.yml
        - studhack-ui/**

  - event: manual

steps:
  - name: UI Dev
    image: woodpeckerci/plugin-docker-buildx
    when:
      - event: pull_request
      - event: manual
        branch:
          exclude: main
    settings:
      repo: ghcr.io/siberianbearofficial/studhack-ui
      registry: ghcr.io
      username: siberianbearofficial
      password:
        from_secret: GITHUB_TOKEN
      context: studhack-ui
      dockerfile: studhack-ui/Dockerfile
      tag: dev

  - name: UI Prod
    image: woodpeckerci/plugin-docker-buildx
    when:
      - event: push
        branch: main
      - event: manual
        branch: main
    settings:
      repo: ghcr.io/siberianbearofficial/studhack-ui
      registry: ghcr.io
      username: siberianbearofficial
      password:
        from_secret: GITHUB_TOKEN
      context: studhack-ui
      dockerfile: studhack-ui/Dockerfile
      tag: main
